### ISSUE TITLE
Strings letter case consistency with Moodle core

### ISSUE THREAD

**Issue by mudrd8mz** [GopalSharma/moodle-auth_azureb2c#1]
As per https://docs.moodle.org/dev/Plugin_contribution_checklist#Strings the English language pack (lang/en/) in Moodle should not use "Capitalised Titles.

Your strings like "Forgot Password Endpoint", "Provider Name" and all others, violate this style.

**Comment by GopalSharma** [comment]
Hi David,
I have resolved the issue. if you find the issue, Please go ahead open it again.
Thank you
