### ISSUE TITLE
The "Azure B2C scope" field currently appears to be a "text" and not a "text area"

### ISSUE THREAD

**Issue by gabrieleMorabito** [GopalSharma/moodle-auth_azureb2c#15]
Hi Gopal,
the "Azure B2C scope" field currently appears to be a "text" field whereas in the pictures you posted it appears to be a "text area" field.

If I have to insert several scopes, how does the system separate them from each other? Do I have to separate them with a comma?

![immagine](https://user-images.githubusercontent.com/34000501/166476663-57917e00-d722-4f87-86d7-4dbfc2624da2.png)

e.g:
openid https://testcosumer.onmicrosoft.com/moodle/write,
https://testcosumer.onmicrosoft.com/moodle/read,
https://testcosumer.onmicrosoft.com/moodle/offline_access,
https://testcosumer.onmicrosoft.com/moodle/user_impersonation,

Tnks for the help!

**Comment by gabrieleMorabito** [comment]
**-- SOLVED --**
Although the 'azure B2c scope' is not a text area field as shown in the images in the documentation, it is simply necessary to separate the different scopes with a space.

Everything works perfectly, thank you for your contribution!

example:
https://testcosumer.onmicrosoft.com/moodle/write https://testcosumer.onmicrosoft.com/moodle/read https://testcosumer.onmicrosoft.com/moodle/offline_access https://testcosumer.onmicrosoft.com/moodle/user_impersonation openid

**Comment by GopalSharma** [comment]
Thank you so much @gabrieleMorabito for finding out this information. I would put _**openeid**_ first and the rest of the scopes after that and separate each scopese by the space. I believe I have already shared this information in one of the plugin screenshots.
I love to contribute to the open-source community as much as possible.
