### ISSUE TITLE
Strack Trace Error

### ISSUE THREAD

**Issue by lucasmellos** [GopalSharma/moodle-auth_azureb2c#4]
Any tutorial or something related to plugin configuration? I've followed all the instructions and once I click on the button then I'm redirected to my callback URL without inserting my Azure B2C credentials.
```
Stack trace:

    line 187 of /auth/azureb2c/classes/loginflow/authcode.php: moodle_exception thrown
    line 107 of /auth/azureb2c/classes/loginflow/authcode.php: call to auth_azureb2c\loginflow\authcode->handleauthresponse()
    line 105 of /auth/azureb2c/auth.php: call to auth_azureb2c\loginflow\authcode->handleredirect()
    line 29 of /auth/azureb2c/index.php: call to auth_plugin_azureb2c->handleredirect()
```

**Comment by GopalSharma** [comment]
Hi Lucas,
There isn't any tutorial available as of now. Can you please list down the instruction you followed?
This plugin has been working absolutely fine for me from the last 6 months. 

I tested it again after seen your issue and found it working well for me.
I'm confident that you have not configured your B2C settings properly.
I'm assuming, you are well aware of configuring Azure B2C, setting a reply URL, creating Policies, etc?
Please share the screenshot of the value you have put in the settings of this plugin along with B2C.
You have not configured your Azure as required to be.
I'm attaching the screenshot of settings that need to be added to this plugin, once you configured your azure portal
<img width="793" alt="setting 1" src="https://user-images.githubusercontent.com/1146458/80660063-4aa9c400-8aa8-11ea-957b-43a99a70e510.PNG">
<img width="707" alt="setting 2" src="https://user-images.githubusercontent.com/1146458/80660065-4bdaf100-8aa8-11ea-9854-480180052bed.PNG">
<img width="724" alt="setting 3" src="https://user-images.githubusercontent.com/1146458/80660066-4c738780-8aa8-11ea-8feb-d3cc68b2c61d.PNG">


.

**Comment by GopalSharma** [comment]
@lucasmellos issue was related to the scope. 
Please see his response in this thread [Azure B2C IDP for moodle](https://moodle.org/mod/forum/discuss.php?d=388317)
