### ISSUE TITLE
Error in Azure AD B2C Connect

### ISSUE THREAD

**Issue by rdudyk** [GopalSharma/moodle-auth_azureb2c#6]
Hi, I've tried deploy B2C plugin to moodle - code flow 
I configured it but i have problem. When moodle receive response to https://moodlesite/moodle/auth/azureb2c/ from the auhorization endpoint with code then appear error "Error in Azure AD B2C Connect".

I tested this code with postman and I sent this code with all required information to token endpoint and token endpoint issue me good token.

So It looks like moodle plugin doesn't know what should do with received code from azure endpoint.

**Comment by GopalSharma** [comment]
Hi @rdudyk 
Explained your issue at the following link.
[https://moodle.org/mod/forum/discuss.php?d=388317#p1646065](https://moodle.org/mod/forum/discuss.php?d=388317#p1646065)
There is absolutely nothing wrong with the plugin code.
Thanks

**Comment by GopalSharma** [comment]
Hi @rdudyk 
Explained your issue at the following link.
[https://moodle.org/mod/forum/discuss.php?d=388317#p1646065](https://moodle.org/mod/forum/discuss.php?d=388317#p1646065)
There is absolutely nothing wrong with the plugin code.
Thanks
