### ISSUE TITLE
Pre-populated email field possible

### ISSUE THREAD

**Issue by itenginex** [GopalSharma/moodle-auth_azureb2c#7]
After authenticating/creating an new user with the plugin the email address field is not pre-populated as expected. Instead new users are asked to complete the profile including email verification.
Is there a way to have this field pre-populated taking the email address provided by B2C directory (and optionally skip email verification)?
![image](https://user-images.githubusercontent.com/60217421/93095632-a2397c80-f6a3-11ea-9f59-751e89c1d811.png)

**Comment by GopalSharma** [comment]
Hi @itenginex ,
You are not sending the application back to Moodle. See the following images to select application claims in your policy.

![B2C_app_claims](https://user-images.githubusercontent.com/1146458/93357850-6696e200-f85e-11ea-8759-49ba6f0bf61b.png)

![B2C_app_claims2](https://user-images.githubusercontent.com/1146458/93358055-a78ef680-f85e-11ea-8312-1cf23ee8ce6b.png)



No, there isn't any wat to skip email address.
