### ISSUE TITLE
Column 'token' cannot be null

### ISSUE THREAD

**Issue by marbmp** [GopalSharma/moodle-auth_azureb2c#8]
After the redirect back from the SSO, I receive the error Column 'token' cannot be null.

What should I do to fix this issue?

**Comment by emyb2** [comment]
For me, I need the token to be id_token as the tokenparams don't have access_token, only id_token. Inspecting the JWT token the value we need is there

<img width="577" alt="Screen Shot 2021-06-18 at 11 55 42 AM" src="https://user-images.githubusercontent.com/14080126/122485909-21d9ea80-d02c-11eb-9d5b-ff0a2a1ccc61.png">

**Comment by ac-tech-madcoz** [comment]
Please refer to the issue logged in Azure AD B2C project:
https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/140

The solution is to append the client_id after the openid scope

**Comment by GopalSharma** [comment]
@emyb2 I have included your change. Closing this issue.

**Comment by geoffreyvanwyk** [comment]
Thank you @GopalSharma! Could you please release it to the plugins directory?
